version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/Idea-Archive-Server/
    
permissions:
- object: /
   pattern: "**"
   owner: ubuntu
   group: ubuntu
   
hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 3000
      runas: ubuntu
  AfterInstall:
    - location: scripts/initialize.sh
      timeout: 3000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 3000
      runas: ubuntu
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 3000
      runas: ubuntu
