spring:
  datasource:
    url: jdbc:mysql://ia-database.clkvi3qkonzd.ap-northeast-2.rds.amazonaws.com:3306/IdeaArchive?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ia_user
    password: 4f1SeO8lRdnoox2PiL5I
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        file-size-threshold: 1MB
        max-file-size: 100MB
        max-request-size: 100MB

  main:
    allow-bean-definition-overriding: 'true'