spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        file-size-threshold: 1MB
        max-file-size: 100MB
        max-request-size: 100MB
    open-in-view: false

  profiles:
    active: local

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: ${EMAIL_HOST}
    username: ${EMAIL_NAME}
    password: ${EMAIL_PASSWORD}
    port: ${EMAIL_PORT}

  main:
    allow-bean-definition-overriding: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

auth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_SECRET}
    redirect-url: ${GOOGLE_REDIRECT_URL}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URL}
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_SECRET}
    redirect-url: ${GITHUB_REDIRECT_URL}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}