spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        file-size-threshold: 1MB
        max-file-size: 100MB
        max-request-size: 100MB
    open-in-view: false

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: ${EMAIL_HOST}
    username: ${EMAIL_NAME}
    password: ${EMAIL_PASSWORD}

  main:
    allow-bean-definition-overriding: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

auth:
  google:
    base-url: ${GOOGLE_BASE_URL}
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_SECRET}
    redirect-url: ${GOOGLE_REDIRECT_URL}
  github:
    base-url: ${GITHUB_BASE_URL}
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_SECRET}
    redirect-url: ${GITHUB_REDIRECT_URL}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}