name: Spring Boot & Gradle CD 

on:
  push:
    branches: [ "master" ]
  
jobs:
  CI:
    uses: ./.github/workflows/ia-server-ci.yml
    secrets: inherit     
  
  prod-CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: make application.yml
        if: true
        run: |
          cd ./src/main/resources
          rm -rf ./application.yml
          touch ./application.yml
          echo "${{ secrets.IA_BACKEND_ENV }}" > ./application.yml
        shell: bash
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name : Setup Gradls's permission
        run : chmod +x gradlew 
      
      - name: Build with Gradle
        run : ./gradlew clean build --exclude-task test
     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ap-northeast-2

      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ia-codedeploy \
            --ignore-hidden-files \
            --s3-location s3://ia-s3-bucket/$GITHUB_SHA.zip \
            --source .

      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ia-codedeploy \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ia-codedeploy-group \
            --s3-location bucket=ia-s3-bucket,key=$GITHUB_SHA.zip,bundleType=zip
            
      - name: IA Backend CD Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ Idea Archieve Backend CD success ✅
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 00FF00

      - name: IA Backend CD Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ Idea Archieve Backend CD failed ❗️
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: FF0000     
